### ISSUE TITLE
Storybook build output folder

### ISSUE THREAD

**Issue by niedzielnyaniol** [arturbien/React95#10]
https://github.com/arturbien/React95/blob/eb6b8f98bb36da6b3733c5c128dac8f9112cc297/package.json#L27

Are you sure that you want to build your storybook into `docs` folder and keep it in git repo?

**Comment by arturbien** [comment]
Any suggestions? 😊 is there something wrong with the current approach? thanks for getting involved

**Comment by niedzielnyaniol** [comment]
[Storybook recommendation](https://storybook.js.org/docs/basics/exporting-storybook/)
> This will build the storybook configured in the Storybook directory into a static web app and place it inside the .out directory. Now you can deploy the content in the .out directory wherever you want.

For me `docs/` should contains `*.md` files in most cases.
What about building storybook - i would set out dir to `.out/` and keep it in `.gitignore` then add `build:storybook` to `release` command in your `package.json` scripts that update storybook after publishing new release

**Comment by maracuja-juice** [comment]
You can of course change it but I don't see what this project gains from it right now.

**Comment by arturbien** [comment]
@niedzielnyaniol for now I think it's all good. Right now only documentation we have is the storybook so let it be 😊
