### ISSUE TITLE
TextArea function "onChange" not triggered

### ISSUE THREAD

**Issue by ReactGirl** [arturbien/React95#11]
The onChange function is not working with TextArea component. Changing to a normal input or Reac95 TextField component as ABA Testing works fine.

Code below:

```jsx harmony
import React, { useState } from "react";
import { TextArea, Button } from "react95";
import { newMessage } from "../state/action";
import styled from "styled-components";

const ButtonBar = styled.div`
  margin: 10px 0;
`;

function PublishMessage(props) {
  const { dispatch } = props;
  const [text, setText] = useState("");

  const updateText = event => {
    console.log(event.target.value); // **** ISSUE: Never Triggered ****
    setText(event.target.value);
  };

  const publishMessage = () => {
    dispatch(newMessage(text));
  };

  const handleKeyPress = event => {
    if (event.key === "Enter") {
      publishMessage();
    }
  };
  return (
    <div>
      <h3>got something to say? </h3>
      <div
        style={{
          padding: "5px 0",
          background: "#ced0cf"
        }}
      >
        <TextArea // ****changing this to "input" or "TextField" proof that component is ok ****
          value={text}
          onChange={updateText}
          placeholder="Type in here.."
          onKeyPress={handleKeyPress}
        />
        <ButtonBar>
          <Button onClick={publishMessage}>Publish it!</Button>
        </ButtonBar>
      </div>
    </div>
  );
}

export default PublishMessage;


```

**Comment by arturbien** [comment]
Yes I found the issue. There is a missing exclamation mark before 'disabled ' check in TextArea code:
`onChange={ disabled && onChange ? onChange : undefined }`
By the way, we have to make use of hooks  in TextArea so it is self-controlled (just like it's done in [TextField](https://github.com/arturbien/React95/blob/master/src/components/TextField/TextField.js)). Would you like to solve the issue? 😊

**Comment by arturbien** [comment]
@ReactGirl  I just fixed the problem, so install newer version of React95 and it will work. Also, I mentioned you in [storybook](https://arturbien.github.io/React95/?selectedKind=TextArea&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel). Thanks for being active here 🚀
