### ISSUE TITLE
Create DigitDisplay component

### ISSUE THREAD

**Issue by arturbien** [arturbien/React95#127]
<img width="560" alt="Screenshot 2020-04-01 at 18 40 31" src="https://user-images.githubusercontent.com/28541613/78163431-aac92e00-7448-11ea-8cd8-57d3e43984c5.png">

**Comment by gabecar** [comment]
hi! can i work on this?

**Comment by arturbien** [comment]
@gabecar actually I pretty much finished the component already. I forgot to assign myself to the task. sorry!
