### ISSUE TITLE
Missing 2px margin right on WindowContent

### ISSUE THREAD

**Issue by benwiley4000** [arturbien/React95#16]
`WindowHeader` has a 2px right margin and for consistency it seems like `WindowContent` should have the same right margin. It looks a bit funny without. (I'm negating padding for my use case since the original player doesn't have any padding).

Without the 2px content margin:

![Screenshot from 2019-04-21 01-23-40](https://user-images.githubusercontent.com/13558253/56465808-7776c600-63d4-11e9-90b9-8065495199c6.png)

With the 2px content margin added:

![Screenshot from 2019-04-21 01-23-32](https://user-images.githubusercontent.com/13558253/56465809-7e053d80-63d4-11e9-875f-2021b1759816.png)

**Comment by arturbien** [comment]
@benwiley4000 thanks for the heads up! Just commited the changes. It will be fixed in the next version 😊

**Comment by benwiley4000** [comment]
Thanks!
