### ISSUE TITLE
Vertical divider would be nice

### ISSUE THREAD

**Issue by benwiley4000** [arturbien/React95#17]
As seen here:

![Screenshot from 2019-04-21 16-59-18](https://user-images.githubusercontent.com/13558253/56475678-94091180-6459-11e9-949a-afb4813abfc9.png)

I implemented something based on the existing divider component here:

```jsx
const React = require('react');
const propTypes = require('prop-types');
const { themes } = require('react95');

const style = {
  width: 0,
  borderRight: `2px solid ${themes.default.borderLightest}`,
  borderLeft: `2px solid ${themes.default.borderDark}`,
  margin: 0,
  alignSelf: 'stretch',
  marginTop: -4,
  marginBottom: -4
};

const VerticalDivider = () => {
  return <div style={style} />;
};

module.exports = VerticalDivider;
```

The negative top/bottom margins are to account for the padding in the Toolbar component.

This is what it looks like:

![Screenshot from 2019-04-21 17-31-12](https://user-images.githubusercontent.com/13558253/56475786-5e652800-645b-11e9-8cf3-171eb98a2938.png)

**Comment by arturbien** [comment]
@benwiley4000 yes that would be great! can you make a pull request for that? You should be shown in the contributors list 🎉

**Comment by benwiley4000** [comment]
Hey @arturbien sorry for not getting back on this.. but I appreciate you implementing this feature thank you!

**Comment by arturbien** [comment]
@benwiley4000 no problem! I will try to add some more things before I release new version with updated <Divider /> so be patient

**Comment by benwiley4000** [comment]
Thanks, let me know when you do release! I fixed my version of react95 for now because the 2px windowcontent width change will actually be a breaking change for me, since I already patched it locally.. haha.
