### ISSUE TITLE
yarn or npm

### ISSUE THREAD

**Issue by maracuja-juice** [arturbien/React95#18]
There is both a yarn.lock and a package-lock.json. The two don't play well together out of experience. Should we use yarn or npm to contribute to this project?

**Comment by arturbien** [comment]
Please use NPM. 😊

**Comment by maracuja-juice** [comment]
Okay. We should delete the yarn.lock in that case then.

**Comment by arturbien** [comment]
@maracuja-juice I just did that in the last commit. Thanks for the heads up!
