### ISSUE TITLE
Update styled-components peer dep to v5

### ISSUE THREAD

**Issue by maxquinn** [arturbien/React95#183]
Relevant features of styled components v5:
- 19% smaller bundle size
- 18% faster client-side mounting
- 17% faster updating of dynamic styles
- 45% faster server-side rendering

There are also no breaking changes from v4 -> v5.
Happy to open a PR if this is wanted?

**Comment by arturbien** [comment]
@maxquinn thanks for the heads up! and yeah sure I will happily accept your PR ♥️
