### ISSUE TITLE
Font license

### ISSUE THREAD

**Issue by SvizelPritula** [arturbien/React95#189]
Is the MS Sans Serif font provided in the distribution freely usable, or is it copyrighted by Microsoft? Similarly, what about the hourglass?

**Comment by SvizelPritula** [comment]
Ok, thanks. Relatedly, is there a suitable font with better international support?

**Comment by arturbien** [comment]
@SvizelPritula see if this font satisfies your needs: https://fontsarena.com/w95fa-by-fontsarena/ . seems like it has more characters than the ones we use
