### ISSUE TITLE
Cutout component not looking good on the docs 

### ISSUE THREAD

**Issue by luizbaldi** [arturbien/React95#192]
The `Cutout` component is not looking exactly like we want, this is probably related to styling and might be a good opportunity for a first contribution.

Current looking:
<img width="350" alt="Screen Shot 2020-10-06 at 09 53 09" src="https://user-images.githubusercontent.com/17226904/95204153-14d8dc00-07ba-11eb-95c7-22507beda989.png">

Expected looking (you can check [storybook](https://storybook.react95.io/?path=/story/cutout--default)):
<img width="396" alt="Screen Shot 2020-10-06 at 09 52 45" src="https://user-images.githubusercontent.com/17226904/95204112-07235680-07ba-11eb-990c-a1badc12e705.png">

### How to reproduce:
1. Fork and clone the repo
2. Install the necessary dependêncies using npm (run `npm i` on the root folder) 
3. Start docs locally by running `npm run docs:dev`, this will start a local server running the documentation on `http://localhost:3000/`
4. Navigate to the `Cutout` component through the Menu (Components > Cutout)

### Aditional information
This documentation was written using [Docz](https://www.docz.site) and we structured it following the [colocation](https://kentcdodds.com/blog/colocation) idea, so every component folder has its own documentation file, and everything generally related to the documentation can be found at the `docs/` folder _or_ (this is a known problem) `src/gatsby-theme-docz` that has some Docz only related files used to extend the documentation behavior.

--- 

Before start working on this bug leave a comment here so we can avoid more than one person working on the issue, if you have any doubts feel free to drop a comment here or join us at [Slack](https://join.slack.com/t/react95/shared_invite/enQtOTA1NzEyNjAyNTc4LWYxZjU3NWRiMWJlMGJiMjhkNzE2MDA3ZmZjZDc1YmY0ODdlZjMwZDA1NWJiYWExYmY1NTJmNmE4OWVjNWFhMTE) 🕺

**Comment by branopuzder** [comment]
Hello, can I work on it?

**Comment by luizbaldi** [comment]
@branopuzder Of course, thank you! Feel free to drop questions/comments here if you need anything 🚀

**Comment by branopuzder** [comment]
Hey there. I've found the problem and fixed it. Should I run `npm run docs:build` before creating a PR or will it be done on Github? Sorry for asking such a question, I'm quite new into it.

**Comment by luizbaldi** [comment]
@branopuzder Sorry for the delay, you don't need to run `npm run docs:build` because this is being taken care of by the CI, thanks for asking and for working on this, looking forward for your PR!

**Comment by branopuzder** [comment]
Hey there! I made a new PR #204 as you asked @arturbien You can check it.
