### ISSUE TITLE
add Tree component

### ISSUE THREAD

**Issue by arturbien** [arturbien/React95#209]

**Comment by ruohki** [comment]
[Win95 Tree View](https://i.gyazo.com/e414311649e3067ed0676956179fa36b.jpg)
for reference

**Comment by arturbien** [comment]
@ruohki want to take care of this task? ☺️

**Comment by alpavlove** [comment]
@arturbien I'd like to take care of this

**Comment by arturbien** [comment]
@alpavlove awesome! Let's go then

**Comment by alpavlove** [comment]
@arturbien I've made something and would be happy to receive feedback. Thanks
