### ISSUE TITLE
Add themes by tPenguinLTG

### ISSUE THREAD

**Issue by tpenguinltg** [arturbien/React95#213]
Port the color schemes of select [Windows Classic themes by tPenguinLTG](https://www.deviantart.com/tpenguinltg/gallery/52576127/windows-classic). It would be easiest to port after work for #212 is completed.

See also: tpenguinltg/winclassic#5

**Comment by arturbien** [comment]
@tpenguinltg maybe lets just put screenshots of available themes here and then we'll decide?

**Comment by tpenguinltg** [comment]
Collapsed so that it won't take up too much space. Most of these are also available in the link in my original message, but I think some haven't been published yet (if we choose them, I'll publish them so we have something to link to). I don't know how well the flat themes will port, but they _should_ be okay if the mapping was correct.

<details><summary>Aiee</summary>

![Aiee](https://user-images.githubusercontent.com/8697332/103968077-405cc100-5131-11eb-8f01-dfbe544d6efe.png)

</details>
<details><summary>Ash</summary>

![Ash](https://user-images.githubusercontent.com/8697332/103968081-40f55780-5131-11eb-803c-023dc4104353.png)

</details>
<details><summary>Blue</summary>

![Blue](https://user-images.githubusercontent.com/8697332/103968082-40f55780-5131-11eb-9209-1009466cc81b.png)

</details>
<details><summary>CGA</summary>

![CGA](https://user-images.githubusercontent.com/8697332/103968083-418dee00-5131-11eb-8548-3bbc8b90ee7a.png)

</details>
<details><summary>Cherry</summary>

![Cherry](https://user-images.githubusercontent.com/8697332/103968085-418dee00-5131-11eb-9356-95df6f33649f.png)

</details>
<details><summary>Clouds</summary>

![Clouds](https://user-images.githubusercontent.com/8697332/103968169-58ccdb80-5131-11eb-80b7-9edbe4e96cf1.png)

</details>
<details><summary>Denim</summary>

![Denim](https://user-images.githubusercontent.com/8697332/103968086-42268480-5131-11eb-9c8e-ad52b19f4129.png)

</details>
<details><summary>Dusk</summary>

![Dusk](https://user-images.githubusercontent.com/8697332/103968087-42268480-5131-11eb-8ad4-c4b1d5d9b7d3.png)

</details>
<details><summary>Fx</summary>

![Fx](https://user-images.githubusercontent.com/8697332/103968088-42268480-5131-11eb-874b-1f646d83a365.png)

</details>
<details><summary>FxDev</summary>

![FxDev](https://user-images.githubusercontent.com/8697332/103968089-42bf1b00-5131-11eb-85c7-98803f9f2e7e.png)

</details>
<details><summary>FxN</summary>

![FxN](https://user-images.githubusercontent.com/8697332/103968090-42bf1b00-5131-11eb-8f80-682ceaa7a566.png)

</details>
<details><summary>Green</summary>

![Green](https://user-images.githubusercontent.com/8697332/103968091-42bf1b00-5131-11eb-8744-9490dd71ecce.png)

</details>
<details><summary>Honey</summary>

![Honey](https://user-images.githubusercontent.com/8697332/103968093-4357b180-5131-11eb-9b97-01208c63c99c.png)

</details>
<details><summary>Hot Chocolate</summary>

![Hot Chocolate](https://user-images.githubusercontent.com/8697332/103968094-4357b180-5131-11eb-96f6-f5ef35e1a5da.png)

</details>
<details><summary>Hotdog Stand</summary>

![Hotdog Stand](https://user-images.githubusercontent.com/8697332/103968095-4357b180-5131-11eb-8f34-ab2151d13037.png)

</details>
<details><summary>Ink Pen</summary>

![Ink Pen](https://user-images.githubusercontent.com/8697332/103968096-43f04800-5131-11eb-9da8-01ccff725058.png)

</details>
<details><summary>Malic Platinum</summary>

![Malic Platinum](https://user-images.githubusercontent.com/8697332/103968097-43f04800-5131-11eb-8490-6a08db2cac0e.png)

</details>
<details><summary>Monochrome</summary>

![Monochrome](https://user-images.githubusercontent.com/8697332/103968099-43f04800-5131-11eb-99a9-664c3ab8dff4.png)

</details>
<details><summary>Polarized</summary>

![Polarized](https://user-images.githubusercontent.com/8697332/103968100-4488de80-5131-11eb-9929-fbbd94cf6731.png)

</details>
<details><summary>PowerShell</summary>

![PowerShell](https://user-images.githubusercontent.com/8697332/103968101-4488de80-5131-11eb-9105-8e001195b129.png)

</details>
<details><summary>Precision Blue</summary>

![Precision Blue](https://user-images.githubusercontent.com/8697332/103968102-4488de80-5131-11eb-9834-a76b1fe024ae.png)

</details>
<details><summary>Precision Green</summary>

![Precision Green](https://user-images.githubusercontent.com/8697332/103968103-45217500-5131-11eb-8770-ac42fa43e484.png)

</details>
<details><summary>Precision Red</summary>

![Precision Red](https://user-images.githubusercontent.com/8697332/103968104-45217500-5131-11eb-8097-bbaa1c343cac.png)

</details>
<details><summary>Precision Yellow</summary>

![Precision Yellow](https://user-images.githubusercontent.com/8697332/103968105-45217500-5131-11eb-949a-221f04aa627c.png)

</details>
<details><summary>Precision</summary>

![Precision](https://user-images.githubusercontent.com/8697332/103968108-45217500-5131-11eb-8d2e-8fd0a550c248.png)

</details>
<details><summary>Raspberry</summary>

![Raspberry](https://user-images.githubusercontent.com/8697332/103968109-45ba0b80-5131-11eb-8af7-a0446033f172.png)

</details>
<details><summary>Red Wine</summary>

![Red Wine](https://user-images.githubusercontent.com/8697332/103968111-45ba0b80-5131-11eb-9cc8-b42b01e41965.png)

</details>
<details><summary>Seawater Soft</summary>

![Seawater Soft](https://user-images.githubusercontent.com/8697332/103968112-45ba0b80-5131-11eb-937c-10302d8814d6.png)

</details>
<details><summary>Seawater Splash</summary>

![Seawater Splash](https://user-images.githubusercontent.com/8697332/103968113-4652a200-5131-11eb-8d80-467d8ecaf99d.png)

</details>
<details><summary>Seawater</summary>

![Seawater](https://user-images.githubusercontent.com/8697332/103968114-4652a200-5131-11eb-9b6a-ceb86a7c164d.png)

</details>
<details><summary>Solarized Dark</summary>

![Solarized Dark](https://user-images.githubusercontent.com/8697332/103968115-4652a200-5131-11eb-98d2-73787ff07714.png)

</details>
<details><summary>Solarized Light</summary>

![Solarized Light](https://user-images.githubusercontent.com/8697332/103968117-46eb3880-5131-11eb-98fe-e25551a89cae.png)

</details>
<details><summary>Storm Clouds</summary>

![Storm Clouds](https://user-images.githubusercontent.com/8697332/103968119-46eb3880-5131-11eb-91f2-34f81be7e9a2.png)

</details>
<details><summary>Sunny Day</summary>

![Sunny Day](https://user-images.githubusercontent.com/8697332/103968120-4783cf00-5131-11eb-8efe-32f89b7a4042.png)

</details>
<details><summary>Tango</summary>

![Tango](https://user-images.githubusercontent.com/8697332/103968122-4783cf00-5131-11eb-8172-64e6474ddb79.png)

</details>
<details><summary>Teal for Shelbi - Dark</summary>

![Teal for Shelbi - Dark](https://user-images.githubusercontent.com/8697332/103968124-4783cf00-5131-11eb-976f-64b707321c6e.png)

</details>
<details><summary>Teal for Shelbi</summary>

![Teal for Shelbi](https://user-images.githubusercontent.com/8697332/103968125-481c6580-5131-11eb-814c-d12d996a73d3.png)

</details>
<details><summary>Tomato</summary>

![Tomato](https://user-images.githubusercontent.com/8697332/103968126-481c6580-5131-11eb-8ae6-6bc95bf9cdf3.png)

</details>
<details><summary>Toner</summary>

![Toner](https://user-images.githubusercontent.com/8697332/103968127-481c6580-5131-11eb-9c0e-1fffa4171eed.png)

</details>
<details><summary>Vista-esque Midnight</summary>

![Vista-esque Midnight](https://user-images.githubusercontent.com/8697332/103968128-481c6580-5131-11eb-9631-33d0a87876c2.png)

</details>
<details><summary>Vista-esque</summary>

![Vista-esque](https://user-images.githubusercontent.com/8697332/103968129-48b4fc00-5131-11eb-87c6-c29c9a4bd428.png)

</details>
<details><summary>White</summary>

![White](https://user-images.githubusercontent.com/8697332/103968131-48b4fc00-5131-11eb-8bbc-f304a710974b.png)

</details>
<details><summary>Windows 1</summary>

![Windows 1](https://user-images.githubusercontent.com/8697332/103968132-494d9280-5131-11eb-8be1-5a8c2f4b4253.png)

</details>
<details><summary>wmii</summary>

![wmii](https://user-images.githubusercontent.com/8697332/103968134-494d9280-5131-11eb-863b-6436f263ed73.png)

</details>

**Comment by arturbien** [comment]
@tpenguinltg  So the themes I'd really like to port to React95 are these:

Aiee
Ash
Blue
Cherry
Denim
FxDev
Honey
Hot Chocolate
Hotdog Stand
Polarized
PowerShell
Raspberry
Red Wine
Solarized Dark
Solarized Light
Storm Clouds
Teal for Shelbi - Dark
Teal for Shelbi
Toner
Vista-esque Midnight
White
Windows 1
wmii
