### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by tyler-reitz** [arturbien/React95#26]
I'd be happy to work on the Avatar component but would need some visual guidance. Is there anything to reference?

**Comment by goodmind** [comment]
![DaIcGyWU8AAlbU7](https://user-images.githubusercontent.com/3275424/56937859-5de22680-6b18-11e9-83a5-e3f0cecc4d97.png)

Would need canvas to reduce bit depth tho, or maybe css custom filter

**Comment by arturbien** [comment]
@tyler-reitz @goodmind I think something this simple would be great:

![image](https://user-images.githubusercontent.com/28541613/56951515-56cb1080-6b38-11e9-9379-09c94b4b3302.jpg)

Avatar component is frequently used in AppBars as a user navigation or in chat apps so we could do something similar to [material-ui avatar](https://material-ui.com/demos/avatars/). Also it would be nice to implement the letter avatar too (that's great as a placeholder when user didn't set any profile pic yet) 😊

Maybe we could use canvas like @goodmind mentioned to apply some filters or slightly pixelate the circle edges but that's not essential.

**Comment by goodmind** [comment]
@arturbien but this isn't real app :P

**Comment by arturbien** [comment]
@goodmind yes it's a design. Just like any UI design you get from designers to convert it into something real. 😊

> We are not attempting to exactly RECREATE Windows95 components. We are going to make them usable in the modern mobile / web apps. Thus, any help from UI / UX designers would be EXTREMELY appreciated. The challenge is to come up with new component designs / layouts that are broadly used in modern UIs, that weren't present back in 95.

**Comment by tyler-reitz** [comment]
@arturbien thanks for the notes. That pixelated circle looks :ok_hand: but I'm not sure there's any sane CSS to pull it off with. Maybe the recessed border from @goodmind's ex. would work instead?

**Comment by maracuja-juice** [comment]
@tyler-reitz I looked this up the other day and it should definitely be possible with a canvas.

**Comment by goodmind** [comment]
@tyler-reitz how would this border look on the circle?

**Comment by tyler-reitz** [comment]
@goodmind probably not as good as the example provided by @arturbien. @maracuja-juice says the pixelated border effect is achievable with canvas anyway, so no need to fix what ain't broke.

**Comment by arturbien** [comment]
#30 For now I added simple Avatar component with 'noBorder' and 'square' prop. What do you think?

**Comment by arturbien** [comment]
#30
