### ISSUE TITLE
Allow "100%" width prop in Progress component

### ISSUE THREAD

**Issue by arturbien** [arturbien/React95#44]
Right now `<Progress />` component only accepts number as a width prop (which is then converted to `px`).  Width specified in percent should also be allowed. Progress component should be of 100% width by default.

**Comment by Mrpanquecas** [comment]
I can try and make a PR for that,

would you prefer a simple check like this:

props => props.width ? `${props.width}px` : '100%'

or a little more complex check that allows the user to choose the type of width measurement?
IMO the user should always specify the type and resort to px if none is chosen

**Comment by arturbien** [comment]
@Mrpanquecas I think we could approach it in exact same way as in [`<TextField />`](https://github.com/arturbien/React95/blob/93d107a96f7288759d0c8fdae9fe0061ef0bfbbc/src/components/TextField/TextField.js#L49) component. Same thing should also be done in `<Select />` component. #46. Do you want to solve these issues? 😊 thanks a lot for getting involved!

**Comment by Mrpanquecas** [comment]
Yes i will try to solve this issues ASAP, keep up the really good work

**Comment by Mrpanquecas** [comment]
I've modified the select to be able to get 100% of the width.
the progressbar is a bit more tricky because when you put 100% width in the BlueBar component it gets 100% of the parent so the display of the progress percentage is never placed right. Any ideas to fix this?

also i'm not able to commit (it's my first time contributing ever) how is that process done? (can't push to new/old branches)

**Comment by arturbien** [comment]
@Mrpanquecas ok so for now just make a pull request for the Select component changes (#46). You can see a nice tutorial on how to do it [here](https://github.com/firstcontributions/first-contributions). As for the Progress component- I can take care of that and I will let you know how I solved the issue, ok? 😊

**Comment by arturbien** [comment]
@Mrpanquecas you can check my solution for the Progress component now 😊 basically I used css property `clip-path` so the blue bar is always of 100% width but then I only crop out `percentage` % of its width, so the rest becomes invisible

**Comment by Mrpanquecas** [comment]
Awesome! I will try it out right now in my project! thanks a lot for the explanation!
