### ISSUE TITLE
ESLint configuration

### ISSUE THREAD

**Issue by luizbaldi** [arturbien/React95#50]
That'd be good to have `ESLint` configured for the project, so we can have a pattern for the codebase and help more new contributors.

Any thoughts on famous JavaScript/React style guides to be followed? _(like Airbnb or Standard)_

**Comment by arturbien** [comment]
I always see people using AirBnb settings so I think it might be the best option since many people are used to these settings. But let's wait for some more opinions

**Comment by vnallamhawk** [comment]
Hello @luizbaldi can i take this up ?

**Comment by luizbaldi** [comment]
> Hello @luizbaldi can i take this up ?

Of course! Feel free to ping us on the discord channel if you need anything :)

**Comment by vnallamhawk** [comment]
I am not sure of what is meant by discord channel. Shall we go with airbnb initially ? Should I raise a pull request to master branch with my changes ?

**Comment by arturbien** [comment]
@vnallamhawk yeah lets do AirBnb, and you can do pull request to master too 🤟🏻

**Comment by arturbien** [comment]
closed in #52
