### ISSUE TITLE
Cannot pass ref to TextField

### ISSUE THREAD

**Issue by arturbien** [arturbien/React95#68]
Cannot pass ref to `<TextField />`. Using `React.forwardRef()` doesn't work either.  (Warning shows in console: `Function components cannot be given refs`).

Same thing most probably happens in all other input components

Reproduction of the bug: https://codesandbox.io/s/serene-dan-qx1cj

**Comment by rwachtler** [comment]
Could you assign me to this issue?

**Comment by arturbien** [comment]
@rwachtler of course! also please join our slack (link in the docs) 🔥

**Comment by arturbien** [comment]
closed by #71
